name: generate-swift-dependencies
description: Submit the dependencies of a Swift project to the Github API

inputs:
  path:
    description: The path to the checked-out package to generate dependencies for. Defaults to workspace.
    required: false
    default: ${{ github.workspace }}
  repository:
    description: The Github repo to submit the dependencies to. Defaults to current.
    required: false
    default: ${{ github.repository }}
  branch:
    description: The branch to associate the dependency submission with. Defaults to ref.
    required: false
    default: ${{ github.ref }}
  commit:
    description: The commit from which the dependencies are generated. Defaults to current.
    required: false
    default: ${{ github.sha }}
  token:
    description: Github access token to use for submitting the dependencies.
    required: false
    default: ${{ github.token }}
  metadata:
    required: false
    description: 'User provided map of max 8 key/value pairs of metadata to include with the snapshot e.g. {"lastModified": "12-31-2022"}'

runs:
  using: composite
  steps:
    - name: Convert dependency graph
      id: graph
      env:
        PROJ: ${{ inputs.path || github.workspace }}
        BRANCH: ${{ inputs.branch || github.ref }}
        COMMIT: ${{ inputs.commit || github.sha }}
        CORRELATOR: ${{ github.workflow_ref }}-${{ github.job }}-${{ github.action }}-${{ runner.os }}
        REPO_SPEC: ${{ inputs.repository || github.repository }}
        TOKEN: ${{ inputs.token || github.token }}
      shell: bash
      run: |
        SUDO="$([[ "$(id -un)" == "root" ]] && echo env || echo sudo)"
        if [[ -z "$(command -v curl)" || -z "$(command -v jq)" ]]; then
          $SUDO apt-get -q update && $SUDO apt-get -yq install curl jq
        fi
        # TODO: When SE-0509 is implemented, replace this with that.
        if [[ -z "$(command -v trivy)" ]]; then
          $SUDO curl -qsL -o /etc/apt/keyrings/trivy.asc 'https://aquasecurity.github.io/trivy-repo/deb/public.key'
          $SUDO bash -c 'echo "deb [signed-by=/etc/apt/keyrings/trivy.asc] https://aquasecurity.github.io/trivy-repo/deb generic main" >> /etc/apt/sources.list.d/trivy.list'
          $SUDO apt-get -q update && sudo apt-get -yq install trivy
        fi
        
        # If there's no Package.resolved, we need to generate one.
        if [[ ! -f "${PROJ}/Package.resolved" ]]; then
          swift package --package-path "${PROJ}" --disable-dependency-cache resolve
        fi

        trivy filesystem "${PROJ}" -f github --disable-telemetry --scanners '' --skip-check-update --skip-db-update --skip-dirs .build -q --offline-scan | \
          jq -c --arg sha "${COMMIT}" --arg ref "${BRANCH}" --arg id "${GITHUB_RUN_ID}" --arg cor "${CORRELATOR}" \
                '.sha = $sha | .ref = $ref | .job = { id: $id, correlator: $cor }' |\
          curl -fLv \
            -H 'Accept: application/vnd.github+json' \
            -H 'Content-Type: application/json' \
            -H "Authorization: Bearer ${TOKEN}" \
            -H 'X-GitHub-Api-Version: 2022-11-28' \
            "${GITHUB_API_URL}/repos/${REPO_SPEC}/dependency-graph/snapshots" \
            --data @-
